---
booktitle: 'Proceedings of the First International Workshop on Learning with Imbalanced
  Domains: Theory and Applications'
shortname: LIDTA
sections:
- name: Preface
  title: Preface
- name: Full Papers
  title: Full Papers
- name: Posters
  title: Posters
year: '2017'
volume: 74
start: 2017-09-22
end: 2017-09-22
url: http://proceedings.mlr.press
published: 2017-10-11
layout: proceedings
series: Proceedings of Machine Learning Research
issn: 2640-3498
id: LIDTA2017
month: 0
cycles: false
editor:
- given: Luís
  family: Torgo
- given: Bartosz
  family: Krawczyk
- given: Paula
  family: Branco
- given: Nuno
  family: Moniz
title: Proceedings of Machine Learning Research
description: |
  Proceedings of the First International Workshop on Learning with Imbalanced Domains: Theory and Applications
    Held in ECML-PKDD, Skopje, Macedonia on 22 September 2017

  Published as Volume 74 by the Proceedings of Machine Learning Research on 11 October 2017.

  Volume Edited by:
    Luís Torgo
    Bartosz Krawczyk
    Paula Branco
    Nuno Moniz

  Series Editors:
    Neil D. Lawrence
    Mark Reid
date_str: 22 Sep
baseurl: "/v74"
twitter_username: MLResearchPress
github_username: mlresearch
markdown: kramdown
plugins:
- jekyll-remote-theme
remote_theme: lawrennd/proceedings
permalink: "/:title.html"
ghub:
  edit: true
  repository: v74
display:
  copy_button:
    bibtex: true
    endnote: true
    apa: true
  comments: false
email: ''
conference:
  name: 'First International Workshop on Learning with Imbalanced Domains: Theory
    and Applications'
  url: 
  location: ECML-PKDD, Skopje, Macedonia
  dates:
  - 2017-09-22
analytics:
  google:
    tracking_id: UA-92432422-1
orig_bibfile: "/Users/neil/mlresearch/bibtex.bib"
# Site settings
# Original source:  /Users/neil/mlresearch/bibtex.bib
